version: "3"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
    ports:
      - "5432:5432"
